config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :post
    get 'followers' => 'users#followers'
    get 'following' => 'users#following'
  end
  
  resource :follows, only: %i[create destroy]

  resources :posts do
    resources :likes
    resources :shares
    resources :dislikes
  end

  mount Commontator::Engine => '/commontator'
  mount ActionCable.server => '/cable'

  resources :search, only: [:index]

  get '/c' => 'conversations#index'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: %i[index show]

  resources :contacts
  get '/plans' => 'pages#plan'
  get '/about' => 'pages#about'
  get '/s' => 'pages#search'
  root 'pages#home'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  include PgSearch::Model
  
  pg_search_scope :search, against: [:first_name, :middle_name, :contact_email, :last_name, :phone_number]

  belongs_to :user
    
    has_attached_file :avatar, :styles => {
            :medium => "250*250",
            :thumb => "100*100"
    }, :default_url => "user_default.jpg"

    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    @user = User.find(params[:user_id])
    @profile = Profile.new
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)

    if @profile.save
      flash[:success] = 'Profile Created Successfully.'
      redirect_to user_path(params[:user_id])
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile

    if @profile.update_attributes(profile_params)
      flash[:success] = 'Profile Updated Successfully.'
      redirect_to user_path(params[:user_id])
    else
      render action: :edit
    end
  end

  private

  def profile_params
    params.require('profile').permit(:authenticity_token, :profile, :commit, :user_id, :first_name, :middle_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
  end

  def only_current_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => {:multipart => true} do |f| %>
  <div class="">

    <div class="form-group">
      <%= f.label :first_name, 'First Name' %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :middle_name, 'Middle Name' %>
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, 'Last Name' %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, 'Profile Picture' %>
      <%= f.file_field :avatar, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :job_title, 'Job Title' %>
      <%= f.select :job_title, %w(Developer Entrepreneur Investor), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, 'Phone Number' %>
      <%= f.telephone_field :phone_number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :contact_email, 'Contact Email' %>
      <%= f.email_field :contact_email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <%= f.submit 'Update Profile', class: "btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/profiles/_form.mobile.erb
<%= form_for @profile, url: user_profile_path, :html => {:multipart => true} do |f| %>
  <div class="">

    <div class="form-group">
      <%= f.label :first_name, 'First Name' %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :middle_name, 'Middle Name' %>
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, 'Last Name' %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :avatar, 'Profile Picture' %>
      <%= f.file_field :avatar, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :job_title, 'Job Title' %>
      <%= f.select :job_title, %w(Developer Entrepreneur Investor), {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, 'Phone Number' %>
      <%= f.telephone_field :phone_number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :contact_email, 'Contact Email' %>
      <%= f.email_field :contact_email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <%= f.submit 'Update Profile', class: "btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create your user profile.</h1>
    <p class="text-center">Become a part of the Dev Match community by creating this profile.</p>
    <div class="flash-messages">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
    </div>

    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/edit.mobile.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create your user profile.</h1>
    <p class="text-center">Become a part of the Dev Match community by creating this profile.</p>
    <div class="flash-messages">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
    </div>

    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class=" card">
      <div class="card-header">
        <h1 class="text-center">Create your user profile.</h1>
        <p class="text-center">Become a part of the Dev Match community by creating this profile.</p>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.mobile.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class=" card">
      <div class="card-header">
        <h1 class="text-center">Create your user profile.</h1>
        <p class="text-center">Become a part of the Dev Match community by creating this profile.</p>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>