config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :post
    get 'followers' => 'users#followers'
    get 'following' => 'users#following'
  end
  
  resource :follows, only: %i[create destroy]

  resources :posts do
    resources :likes
    resources :shares
    resources :dislikes
  end

  mount Commontator::Engine => '/commontator'
  mount ActionCable.server => '/cable'

  resources :search, only: [:index]

  get '/c' => 'conversations#index'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: %i[index show]

  resources :contacts
  get '/plans' => 'pages#plan'
  get '/about' => 'pages#about'
  get '/s' => 'pages#search'
  root 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  belongs_to :plan
  has_one :profile
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :personal_messages, dependent: :destroy
  has_many :follower_relationships, class_name: "Follow", foreign_key: "following_id"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :following_relationships, class_name: "Follow", foreign_key: "user_id"
  has_many :following, through: :following_relationships, source: :following
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  
  acts_as_commontator
  attr_accessor :stripe_card_token

  def fullname
    return "#{self.profile.last_name.capitalize} #{self.profile.first_name.capitalize}".to_s
  end

  def follow(user_id)
    following_relationships.create(following_id: user_id)
    follow_update(user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
    follow_update(user_id)
  end

  def follow_update(user_id)
    u = User.find_by(id: user_id)
    u.followers_count = u.followers.length
    u.save! 
    u.followings_count = u.following.length
    u.save!
  end

  def is_following?(user_id)
    relationship = Follow.find_by(user_id: id, following_id: user_id)
    return true if relationship 
  end

  def likes?(post_id)
    well = Like.find_by(user_id: id, post_id: post_id)
    return true if well
  end
  
  def dislikes?(post_id)
    well = Dislike.find_by(user_id: id, post_id: post_id)
    return true if well
  end

  def has_shared?(post_id)
    well = Share.find_by(user_id: id, post_id: post_id)
    return true if well
  end

  def save_with_payment
    if valid?
      print :stripe_card_token
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new

  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end

  private
  def sign_up_params
    params.require(:user).permit(:stripe_card_token, :email, :password, :password_confirmation)
  end

  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2' || params[:plan] == '3')
      flash[:notice] = "Please select a valid membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @pagy, @users = pagy(User.all, items: 18)
    end

    def show
        @user = User.find(params[:id])
        @pagy, @posts = pagy(@user.posts, items: 2)
    end

    def followers
        @pagy, @followers = pagy(User.find_by(id: params[:user_id]).followers, items: 14)
    end
    
    def following 
        @pagy, @following = pagy(User.find_by(id: params[:user_id]).following, items: 14)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # def job_title_icon
    #     if @user.profile
    #         if @user.profile.job_title == "Developer"
    #             "<i class='fa fa-code'></i>".html_safe
    #         elsif @user.profile.job_title == "Entrepreneur"
    #             "<i class='fa fa-lightbulb'></i>".html_safe
    #         elsif @user.profile.job_title == "Entrepreneur"
    #             "<i class='fa fa-institution'></i>".html_safe
    #         end
    #     end
    # end
end

app/views/users/followers.html.erb
<div class="col-md-10 offset-md-1" style="margin-top: 12px">
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <ul class="list-unstyled list-group-flush row">
    <% @followers.each do |follower| %>
      <li class="list-group-item col-sm-5 offset-sm-1">
        <%= link_to follower, class: "card-title" do %>
          <span><%= follower.profile.last_name.upcase %></span>, 
          <span><%= follower.profile.first_name %></span>
          <span><%= follower.profile.middle_name %></span>
        <% end %>
        <span class="text-right">
          <% if !(current_user.is_following?(follower)) %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right' do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right', method: :delete do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Unfollow", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/followers.mobile.erb
<div class="col-md-10 offset-md-1" style="margin-top: 12px">
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <ul class="list-unstyled list-group-flush row">
    <% @followers.each do |follower| %>
      <li class="list-group-item col-sm-5 offset-sm-1">
        <%= link_to follower, class: "card-title" do %>
          <span><%= follower.profile.last_name.upcase %></span>, 
          <span><%= follower.profile.first_name %></span>
          <span><%= follower.profile.middle_name %></span>
        <% end %>
        <span class="text-right">
          <% if !(current_user.is_following?(follower)) %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right' do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right', method: :delete do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Unfollow", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/following.html.erb
<div class="col-md-10 offset-md-1" style="margin-top: 12px">
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <ul class="list-unstyled list-group-flush row">
    <% @following.each do |follower| %>
      <li class="list-group-item col-sm-5 offset-sm-1">
        <%= link_to follower, class: "card-title" do %>
          <span><%= follower.profile.last_name.upcase %></span>, 
          <span><%= follower.profile.first_name %></span>
          <span><%= follower.profile.middle_name %></span>
        <% end %>
        <span class="text-right">
          <% if !(current_user.is_following?(follower)) %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right' do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right', method: :delete do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Unfollow", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/following.mobile.erb
<div class="col-md-10 offset-md-1" style="margin-top: 12px">
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <ul class="list-unstyled list-group-flush row">
    <% @following.each do |follower| %>
      <li class="list-group-item col-sm-5 offset-sm-1">
        <%= link_to follower, class: "card-title" do %>
          <span><%= follower.profile.last_name.upcase %></span>, 
          <span><%= follower.profile.first_name %></span>
          <span><%= follower.profile.middle_name %></span>
        <% end %>
        <span class="text-right">
          <% if !(current_user.is_following?(follower)) %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right' do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <% @follow = Follow.new %>
            <%= form_for (@follow), class: 'text-right', method: :delete do |f| %>
              <%= hidden_field_tag :user_id, follower.id %>
              <%= f.submit "Unfollow", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="custom-title text-center">Dev Match Community</h1>
  <br />
  <% if !Profile.find_by_user_id(current_user.id) %>
    <p class="text-center">Users must create a profile in order to be visible.</p>
  <% end %>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <div class="card-columns xx">
    <% @users.each do |u| %>
      <% if u.profile %>
        <div class="card"  style="width: 18rem; margin: 0 0 12px;">
          <div class="card-header">
            <span>
              <% if u.plan_id == 3 %>
                <span class="label label-danger">PRO</span>
              <% end %>
              <%= u.profile.job_title.capitalize %>
            </span>
          </div>
          <%= link_to u, class: "custom-link" do %>
            <%= image_tag u.profile.avatar.url(:medium), class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <%= link_to u, class: "card-title" do %>
              <span><%= u.profile.last_name.upcase %>, </span>
              <span><%= u.profile.first_name.capitalize %></span>
              <span><%= u.profile.middle_name.capitalize %></span>
            <% end %>
            <div class="card-text">
              <% if current_user.plan_id == 3 %>
                <div>
                  <span><%= u.profile.phone_number %></span>
                </div>
                <div>
                  <span><%= u.profile.contact_email %></span>
                </div>
              <% end %>
              <div><%= u.profile.description %></div>
            </div>
          </div>
          <div class="card-footer">
            <div class="text-left">
              <span><%= u.followers_count %> followers </span>
              <span><%= u.followings_count %> following</span>
            </div>
            <div class="text-left">
              <% if !(current_user.is_following?(u)) %>
                <% @follow = Follow.new %>
                <%= form_for (@follow) do |f| %>
                  <%= hidden_field_tag :user_id, u.id %>
                  <%= f.submit "Follow", class: "btn btn-primary" %>
                <% end %>
              <% else %>
                <% @follow = Follow.new %>
                <%= form_for (@follow), method: :delete do |f| %>
                  <%= hidden_field_tag :user_id, u.id %>
                  <%= f.submit "Unfollow", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/index.mobile.erb
<div class="container">
  <h1 class="custom-title text-center">Dev Match Community</h1>
  <br />
  <% if !Profile.find_by_user_id(current_user.id) %>
    <p class="text-center">Users must create a profile in order to be visible.</p>
  <% end %>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <div class="card-columns xx">
    <% @users.each do |u| %>
      <% if u.profile %>
        <div class="card"  style="width: 18rem; margin: 0 0 12px;">
          <div class="card-header">
            <span>
              <% if u.plan_id == 3 %>
                <span class="label label-danger">PRO</span>
              <% end %>
              <%= u.profile.job_title.capitalize %>
            </span>
          </div>
          <%= link_to u, class: "custom-link" do %>
            <%= image_tag u.profile.avatar.url(:medium), class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <%= link_to u, class: "card-title" do %>
              <span><%= u.profile.last_name.upcase %>, </span>
              <span><%= u.profile.first_name.capitalize %></span>
              <span><%= u.profile.middle_name.capitalize %></span>
            <% end %>
            <div class="card-text">
              <% if current_user.plan_id == 3 %>
                <div>
                  <span><%= u.profile.phone_number %></span>
                </div>
                <div>
                  <span><%= u.profile.contact_email %></span>
                </div>
              <% end %>
              <div><%= u.profile.description %></div>
            </div>
          </div>
          <div class="card-footer">
            <div class="text-left">
              <span><%= u.followers_count %> followers </span>
              <span><%= u.followings_count %> following</span>
            </div>
            <div class="text-left">
              <% if !(current_user.is_following?(u)) %>
                <% @follow = Follow.new %>
                <%= form_for (@follow) do |f| %>
                  <%= hidden_field_tag :user_id, u.id %>
                  <%= f.submit "Follow", class: "btn btn-primary" %>
                <% end %>
              <% else %>
                <% @follow = Follow.new %>
                <%= form_for (@follow), method: :delete do |f| %>
                  <%= hidden_field_tag :user_id, u.id %>
                  <%= f.submit "Unfollow", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="d-flex flex-row justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% if @user.profile %>
        <div class="card" style="width: 18rem" <%= cycle('white-bg', '') %>>
          <div class="card-header">
            <span>
              <%# <span class="job-title-icon"><%= job_title_icon %></span>
            <%= @user.profile.job_title.capitalize %>
          </span>
        </div>
        <%= image_tag @user.profile.avatar.url(:medium), class: "card-img-top" %>
        <div class="card-body">
          <div class="card-title">
            <span><%= @user.profile.last_name.upcase %>, </span>
            <span><%= @user.profile.first_name.capitalize %></span>
            <span><%= @user.profile.middle_name.capitalize %></span>
          </div>
          <div class="card-text">
            <% if current_user.plan_id == 3 || current_user.id == @user.id %>
              <div>
                <span><%= @user.profile.phone_number %></span>
              </div>
              <div>
                <span><%= @user.profile.contact_email %></span>
              </div>
            <% end %>
            <div>
              <span><%= @user.profile.description %></span>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <div class="text-left">
            <%= link_to user_followers_path(user_id: @user.id) do %>
              <span><%= @user.followers_count %> followers </span>
            <% end %>
            <%= link_to user_following_path(user_id: @user.id) do %>
              <span><%= @user.followings_count %> following</span>
            <% end %>
          </div>
          <% unless current_user.id == @user.id %>
            <div class="text-left d-flex flex-row align-items-center">
              <% if !(current_user.is_following?(@user)) %>
                <%= button_to 'Follow', follows_path(user_id: @user.id), class: 'btn btn-outline-primary' %>
              <% else %>
                <%= button_to 'Unfollow', follows_path(user_id: @user.id), class: 'btn btn-outline-danger', method: :delete %>
              <% end %>
              <%= link_to new_personal_message_path(receiver_id: @user), style: 'margin-left: 4px;font-size: 1.2rem;border-radius: 4rem 4rem;', class: 'btn btn-outline-primary' do %>
                <i class="fas fa-envelope"></i>
              <% end %>
            </div>
          <% end%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8 offset-sm-1">
    <div class="d-flex flex-row flex-wrap justify-content-around">
      <% @posts.each do |p| %>
        <div class="card" style="margin-bottom: 12px; width: 20rem">
          <div class="card-header d-flex flex-row justify-content-between">
            <h5><%= p.title %></h5>
            <%= link_to 'Edit', edit_user_post_path(user_id: p.user_id, id: p.id), class: '', style: "margin-right: 4px",method: :put %>
          </div>
          <%= image_tag p.image_url, class: "card-img-top" %>
          <div class="card-body">
            <h6><%= p.subtitle %></h6>
          </div>
          <div class="card-footer d-flex flex-row align-items-center justify-content-between">
            <span>
              <span>
                <i class="fas fa-heart up-solid"></i>
                <%= p.likes.count %>
              </span>
              <span>
                <i class="fas fa-heart-broken down-solid"></i>
                <%= p.dislikes.count %>
              </span>
              <span>
                <i class="fas fa-retweet share-solid"></i>
                <%= p.shares.count %>
              </span>
            </span>
            <span class="d-flex flex-row text-right">
              <% if current_user.id == p.user_id %>
                <%= button_to 'Delete', user_post_path(user_id: p.user_id, id: p.id), class: 'btn btn-danger', style: "margin-right: 4px",method: :delete %>
              <% end%>
              <span>
                <%= link_to 'View', user_post_path(user_id: p.user_id, id: p.id), class: 'btn btn-primary' %>
              </span>
            </span>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex flex-row justify-content-center">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>
</div>

app/views/users/show.mobile.erb
<div class="cover-image w-100" style="height: 20vh;background: rgba(255, 118, 118, 0.6);">
</div>
<div class="d-flex flex-column align-items-center w-100" style="margin-top: -10vw;">
  <div style="width: 95% !important; d-flex flex-column">
    <%= image_tag @user.profile.avatar.url(:medium), class: "card-img-top", style: "width: 20vw; border-radius: 50%" %>
    <div>
      <span style="font-size: 2.5rem; font-weight: bolder;"><%= @user.profile.last_name.upcase %>, </span>
      <span style="font-size: 2.5rem; font-weight: bolder;"><%= @user.profile.first_name.capitalize %></span>
      <span style="font-size: 2.5rem; font-weight: bolder;"><%= @user.profile.middle_name.capitalize %></span>
    </div>
    <div style="font-size: 2.2rem; color: #4f4f4f"><%= @user.profile.job_title.capitalize %></div>
    <div class="text-dark" style="font-size: 2rem;"><%= @user.profile.description %></div>
    <% if current_user.plan_id == 3 || current_user.id == @user.id %>
      <div>
        <span style="font-size: 1.8rem; color: #000"><%= @user.profile.phone_number %></span>
      </div>
      <div>
        <span style="font-size: 1.8rem; color: #000"><%= @user.profile.contact_email %></span>
      </div>
    <% end %>
    <br>
    <% if current_user.id == @user.id %>
      <%= link_to edit_user_profile_path(user_id: current_user.id), class: 'btn btn-outline-dark', style: 'font-size: 2rem' do %>
        Edit Profile
      <% end %>
    <% else %>
      <div class="text-left d-flex flex-row align-items-center">
        <% if !(current_user.is_following?(@user)) %>
          <%= button_to 'Follow', follows_path(user_id: @user.id), style: "font-size: 2rem",class: 'btn btn-outline-primary' %>
        <% else %>
          <%= button_to 'Unfollow', follows_path(user_id: @user.id), style: "font-size: 2rem",class: 'btn btn-outline-danger', method: :delete %>
        <% end %>
        <%= link_to new_personal_message_path(receiver_id: @user), style: 'margin-left: 4px;font-size: 1.2rem;border-radius: 4rem 4rem;', class: 'btn btn-outline-primary' do %>
          <i class="fas fa-envelope"></i>
        <% end %>
      </div>
    <% end%>
    <div class="d-flex flex-row justify-content-start">
      <%= link_to user_followers_path(user_id: current_user.id) do %>
        <span class="text-dark" style="font-size: 2.2rem;"><%= current_user.followers_count %> <span style="font-size: 2rem; color: #4f4f4f"> followers</span> </span>
      <% end %>
      <%= link_to user_following_path(user_id: current_user.id), style: 'margin-left: 10px' do %>
        <span class="text-dark" style="font-size: 2.2rem;"><%= current_user.followings_count %> <span style="font-size: 2rem; color: #4f4f4f"> following</span> </span>
      <% end %>
    </div>
  </div>
  <div class="">
    <div class="d-flex flex-row flex-wrap justify-content-around">
      <% @posts.each do |p| %>
        <div class="card" style="margin-bottom: 12px; width: 20rem">
          <div class="card-header d-flex flex-row justify-content-between">
            <h5><%= p.title %></h5>
            <%= link_to 'Edit', edit_user_post_path(user_id: p.user_id, id: p.id), class: '', style: "margin-right: 4px",method: :put %>
          </div>
          <%= image_tag p.image_url, class: "card-img-top" %>
          <div class="card-body">
            <h6><%= p.subtitle %></h6>
          </div>
          <div class="card-footer d-flex flex-row align-items-center justify-content-between">
            <span>
              <span>
                <i class="fas fa-heart up-solid"></i>
                <%= p.likes.count %>
              </span>
              <span>
                <i class="fas fa-heart-broken down-solid"></i>
                <%= p.dislikes.count %>
              </span>
              <span>
                <i class="fas fa-retweet share-solid"></i>
                <%= p.shares.count %>
              </span>
            </span>
            <span class="d-flex flex-row text-right">
              <% if current_user.id == p.user_id %>
                <%= button_to 'Delete', user_post_path(user_id: p.user_id, id: p.id), class: 'btn btn-danger', style: "margin-right: 4px",method: :delete %>
              <% end%>
              <span>
                <%= link_to 'View', user_post_path(user_id: p.user_id, id: p.id), class: 'btn btn-primary' %>
              </span>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>