config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :post
    get 'followers' => 'users#followers'
    get 'following' => 'users#following'
  end
  
  resource :follows, only: %i[create destroy]

  resources :posts do
    resources :likes
    resources :shares
    resources :dislikes
  end

  mount Commontator::Engine => '/commontator'
  mount ActionCable.server => '/cable'

  resources :search, only: [:index]

  get '/c' => 'conversations#index'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: %i[index show]

  resources :contacts
  get '/plans' => 'pages#plan'
  get '/about' => 'pages#about'
  get '/s' => 'pages#search'
  root 'pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  belongs_to :User, optional: true
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  
  acts_as_commontable dependent: :destroy

  pg_search_scope :search, against: [:title, :subtitle, :body], using: { tsearch: { dictionary: 'english' } }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :only_current_user, only: [:new, :create, :update, :edit, :destroy]   

  def index
    @posts = Post.all.order('created_at DESC')
  end
  
  def new
    @post = Post.new
    respond_modal_with @post
  end

  def create
    @post = @user.posts.create(post_params.merge(user_id: @user))
    
    if @post.save
      flash[:success] = "Post successfully created"
      respond_modal_with @post, location: request.referrer
    else
      flash[:danger] = "Oops... something went wrong"
      render 'new'
    end
  end

  def show
    post = Post.find(params[:id])
    @user = User.find_by(id: post.user_id)
    
    commontator_thread(post)
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to request.referrer
  end


  private

  def post_params
    params.require(:post).permit(:image_url, :user_id, :title, :subtitle, :body)
  end

  def only_current_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1" style="height: 100%">
    <div class="card" style="height: 100%">
      <div class="card-header text-center">
        New Post
      </div>
      <%= form_for @post, url: user_post_path, :html => {:multipart => true}, method: :patch do |f| %>
        <div class="card-body">
          <%= hidden_field_tag :user_id, current_user.id %>
          <%= hidden_field_tag :id, @post.id %>
          <div class="row" style="margin: 0; padding: 0;">
            <div class="col-md-4 d-flex flex-column">
              <div class="form-group">
                <%= f.label :image_url, 'Post Image' %>
                <%= f.text_field :image_url, class: "form-control" %>
                <%# <%= f.file_field :image_url, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :subtitle, 'Subtitle' %>
                <%= f.text_field :subtitle, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group" style="height: 600px">
                <%= f.label :body %>
                <%= f.text_area :body, style: "height: calc(100% - 40px)", class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= f.submit 'Post', class: "float-right btn btn-dark btn-inline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.mobile.erb
<div class="row">
  <div class="col-md-10 offset-md-1" style="height: 100%">
    <div class="card" style="height: 100%">
      <div class="card-header text-center">
        New Post
      </div>
      <%= form_for @post, url: user_post_path, :html => {:multipart => true}, method: :patch do |f| %>
        <div class="card-body">
          <%= hidden_field_tag :user_id, current_user.id %>
          <%= hidden_field_tag :id, @post.id %>
          <div class="row" style="margin: 0; padding: 0;">
            <div class="col-md-4 d-flex flex-column">
              <div class="form-group">
                <%= f.label :image_url, 'Post Image' %>
                <%= f.text_field :image_url, class: "form-control" %>
                <%# <%= f.file_field :image_url, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :subtitle, 'Subtitle' %>
                <%= f.text_field :subtitle, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group" style="height: 600px">
                <%= f.label :body %>
                <%= f.text_area :body, style: "height: calc(100% - 40px)", class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= f.submit 'Post', class: "float-right btn btn-dark btn-inline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
    <div class="card" style="height: 100%">
      <%= form_for @post, url: user_post_path, :html => {:multipart => true} do |f| %>
        <div class="card-body">
          <%= hidden_field_tag :user_id, current_user.id %>
          <div class="row" style="margin: 0; padding: 0;">
            <div class="col-md-5 d-flex flex-column justify-content-between">
              <div class="form-group">
                <%= f.label :image_url, 'Post Image' %>
                <%= f.text_field :image_url, class: "form-control" %>
                <%# <%= f.file_field :image_url, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :subtitle, 'Subtitle' %>
                <%= f.text_field :subtitle, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-7">
              <div class="form-group" style="height: 100%">
                <%= f.label :body %>
                <%= f.text_area :body, style: "height: calc(100% - 40px)", class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= f.submit 'Post', class: "float-right btn btn-dark btn-inline" %>
        </div>
      <% end %>
    </div>

app/views/posts/new.mobile.erb
    <div class="card" style="height: 100%">
      <%= form_for @post, url: user_post_path, :html => {:multipart => true} do |f| %>
        <div class="card-body">
          <%= hidden_field_tag :user_id, current_user.id %>
          <div class="row" style="margin: 0; padding: 0;">
            <div class="col-md-5 d-flex flex-column justify-content-between">
              <div class="form-group">
                <%= f.label :image_url, 'Post Image' %>
                <%= f.text_field :image_url, class: "form-control" %>
                <%# <%= f.file_field :image_url, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :subtitle, 'Subtitle' %>
                <%= f.text_field :subtitle, class: "form-control" %>
              </div>
            </div>
            <div class="col-md-7">
              <div class="form-group" style="height: 100%">
                <%= f.label :body %>
                <%= f.text_area :body, style: "height: calc(100% - 40px)", class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= f.submit 'Post', class: "float-right btn btn-dark btn-inline" %>
        </div>
      <% end %>
    </div>

app/views/posts/show.html.erb
<div class="jumbotron text-white">
  <div class="container wrapper">
    <div class="display-4">
      <%= @post.title %>
    </div>
    <div class="display-5">
      <%= @post.subtitle %>
    </div>
    <div class="text-right" style="font-size: 1.2rem">
      <span>
        <i class="fas fa-heart"></i>
        <%= @post.likes.count %>
      </span>
      <span>
        <i class="fas fa-heart-broken"></i>
        <%= @post.dislikes.count %>
      </span>
      <span>
        <i class="fas fa-retweet"></i>
        <%= @post.shares.count %>
      </span>
    </div>
  </div>
</div>
<div class="container w-60 text-justify">
  <div class="d-flex flex-row justify-content-between flex-wrap">
    <div class="d-flex flex-row align-items-center">
      <%= link_to @user, class: "text-set card-title" do %>
        <%= image_tag @user.profile.avatar.url(:small), class: "img-thumbnail" %>
      <% end %>
      <div class="d-flex flex-column" style="margin-left: 8px">
        <div class="d-flex flex-row align-items-center" style="margin-bottom: -15px">
          <%= link_to @user, class: "text-set card-title" do %>
            <span><%= @user.profile.last_name.upcase %>, </span>
            <span><%= @user.profile.first_name.capitalize %></span>
            <span><%= @user.profile.middle_name.capitalize %></span>
          <% end %>
          <% if user_signed_in? %>
            <% if !(current_user.is_following?(@user.id)) %>
              <%= button_to 'Follow', follows_path(user_id: @user.id), class: 'btn-set btn-primary' %>
            <% else %>
              <%= button_to 'Unfollow', follows_path(user_id: @user.id), class: 'btn-set btn-danger', method: :delete %>
            <% end %>
          <% end %>
        </div>
        <span style="color: #4b4b4b;"><%= @post.created_at.strftime("%b %-d, %Y") %></span>
      </div>
    </div>
    <div class="align-self-end d-flex flex-row align-items-center" style="font-size: 1.2rem">
      <span>
        <% if user_signed_in? %>
          <% if !(current_user.likes?(@post.id)) %>
            <%= button_to post_likes_path(@post), class: "quick-btn post-like", method: :post do %>
              <i class="fas fa-arrow-circle-up"></i>
            <% end %>
          <% else %>
            <% @like = Like.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_like_path(id: @like.id, post_id: @post.id), class: "quick-btn post-like", method: :delete do %>
              <i class="fas fa-arrow-circle-up up-solid"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if user_signed_in? %>
          <% if (current_user.dislikes?(@post.id)) %>
            <% @dislike = Dislike.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_dislike_path(id: @dislike.id, post_id: @post.id), class: "quick-btn post-dislike", method: :delete do %>
              <i class="fas fa-arrow-circle-down down-solid"></i>
            <% end %>
          <% else %>
            <%= button_to post_dislikes_path(@post), class: "quick-btn post-dislike", method: :post do %>
              <i class="fas fa-arrow-circle-down"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if user_signed_in? %>
          <% if (current_user.has_shared?(@post.id)) %>
            <% @share = Share.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_share_path(id: @share.id, post_id: @post.id), class: "quick-btn post-share", method: :delete do %>
              <i class="fas fa-redo share-solid"></i>
            <% end %>
          <% else %>
            <%= button_to post_shares_path(@post), class: "quick-btn post-share", method: :post do %>
              <i class="fas fa-redo"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
  <br>
  <br>
  <%= simple_format @post.body %>
  <br>
  <br>
  <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
  <%= commontator_thread(@post) %>
</div>
</div>
<style>
  .jumbotron {
    background: url("<%= @post.image_url %>") no-repeat center/cover fixed;
  }
</style>

app/views/posts/show.mobile.erb
<div class="jumbotron text-white">
  <div class="container wrapper">
    <div class="display-4">
      <%= @post.title %>
    </div>
    <div class="display-5">
      <%= @post.subtitle %>
    </div>
    <div class="text-right" style="font-size: 1.2rem">
      <span>
        <i class="fas fa-heart"></i>
        <%= @post.likes.count %>
      </span>
      <span>
        <i class="fas fa-heart-broken"></i>
        <%= @post.dislikes.count %>
      </span>
      <span>
        <i class="fas fa-retweet"></i>
        <%= @post.shares.count %>
      </span>
    </div>
  </div>
</div>
<div class="container w-60 text-justify">
  <div class="d-flex flex-row justify-content-between flex-wrap">
    <div class="d-flex flex-row align-items-center">
      <%= link_to @user, class: "text-set card-title" do %>
        <%= image_tag @user.profile.avatar.url(:small), class: "img-thumbnail" %>
      <% end %>
      <div class="d-flex flex-column" style="margin-left: 8px">
        <div class="d-flex flex-row align-items-center" style="margin-bottom: -15px">
          <%= link_to @user, class: "text-set card-title" do %>
            <span><%= @user.profile.last_name.upcase %>, </span>
            <span><%= @user.profile.first_name.capitalize %></span>
            <span><%= @user.profile.middle_name.capitalize %></span>
          <% end %>
          <% if user_signed_in? %>
            <% if !(current_user.is_following?(@user.id)) %>
              <%= button_to 'Follow', follows_path(user_id: @user.id), class: 'btn-set btn-primary' %>
            <% else %>
              <%= button_to 'Unfollow', follows_path(user_id: @user.id), class: 'btn-set btn-danger', method: :delete %>
            <% end %>
          <% end %>
        </div>
        <span style="color: #4b4b4b;"><%= @post.created_at.strftime("%b %-d, %Y") %></span>
      </div>
    </div>
    <div class="align-self-end d-flex flex-row align-items-center" style="font-size: 1.2rem">
      <span>
        <% if user_signed_in? %>
          <% if !(current_user.likes?(@post.id)) %>
            <%= button_to post_likes_path(@post), class: "quick-btn post-like", method: :post do %>
              <i class="fas fa-arrow-circle-up"></i>
            <% end %>
          <% else %>
            <% @like = Like.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_like_path(id: @like.id, post_id: @post.id), class: "quick-btn post-like", method: :delete do %>
              <i class="fas fa-arrow-circle-up up-solid"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if user_signed_in? %>
          <% if (current_user.dislikes?(@post.id)) %>
            <% @dislike = Dislike.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_dislike_path(id: @dislike.id, post_id: @post.id), class: "quick-btn post-dislike", method: :delete do %>
              <i class="fas fa-arrow-circle-down down-solid"></i>
            <% end %>
          <% else %>
            <%= button_to post_dislikes_path(@post), class: "quick-btn post-dislike", method: :post do %>
              <i class="fas fa-arrow-circle-down"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if user_signed_in? %>
          <% if (current_user.has_shared?(@post.id)) %>
            <% @share = Share.find_by(post_id: @post.id, user_id: current_user.id) %>
            <%= button_to post_share_path(id: @share.id, post_id: @post.id), class: "quick-btn post-share", method: :delete do %>
              <i class="fas fa-redo share-solid"></i>
            <% end %>
          <% else %>
            <%= button_to post_shares_path(@post), class: "quick-btn post-share", method: :post do %>
              <i class="fas fa-redo"></i>
            <% end %>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
  <br>
  <br>
  <%= simple_format @post.body %>
  <br>
  <br>
  <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
  <%= commontator_thread(@post) %>
</div>
</div>
<style>
  .jumbotron {
    background: url("<%= @post.image_url %>") no-repeat center/cover fixed;
  }
</style>